name: Steam Parallel Parser

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' 

jobs:
  parse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - start: 0
            count: 500
          - start: 500
            count: 500
          - start: 1000
            count: 500
          - start: 1500
            count: 500
          - start: 2000
            count: 500
          - start: 2500
            count: 500
          - start: 3000
            count: 500
          - start: 3500
            count: 500
          - start: 4000
            count: 500
          - start: 4500
            count: 500

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Обновили до v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Обновили до v5

      - name: Install dependencies
        run: pip install requests

      - name: Run Parser
        run: python parser.py ${{ matrix.start }} ${{ matrix.count }}

      - name: Upload Data
        uses: actions/upload-artifact@v4 # ТУТ БЫЛА ОШИБКА, теперь v4
        with:
          name: results-chunk-${{ matrix.start }} # Имя должно быть уникальным
          path: result_${{ matrix.start }}.json
