name: Steam Parallel Parser

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' 

permissions:
  contents: read

jobs:
  parse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - start: 0
            count: 500
          - start: 500
            count: 500
          - start: 1000
            count: 500
          - start: 1500
            count: 500
          - start: 2000
            count: 500
          - start: 2500
            count: 500
          - start: 3000
            count: 500
          - start: 3500
            count: 500
          - start: 4000
            count: 500
          - start: 4500
            count: 500

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Исправлено: теперь предупреждение о версии исчезнет

      - name: Install dependencies
        run: pip install requests

      - name: Run Parser
        # Мы добавили вывод текущей папки, чтобы ты видел, есть ли там файлы
        run: |
          ls -l
          python parser.py ${{ matrix.start }} ${{ matrix.count }}

      - name: Upload Data
        uses: actions/upload-artifact@v4
        with:
          name: results-chunk-${{ matrix.start }}
          path: result_${{ matrix.start }}.json
          if-no-files-found: warn
